import { NextResponse } from 'next/server';

export async function GET() {
  const data = {
    "products": [
      {
        "id": 1,
        "name": "Floral Summer Skirt",
        "slug": "floral-summer-skirt",
        "category": "Skirt",
        "price": 45.00,
        "originalPrice": 65.00,
        "discount": 30,
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500",
        "description": "Lightweight floral print skirt perfect for summer days",
        "rating": 4.5,
        "inStock": true,
        "colors": ["Pink", "Blue", "Yellow"],
        "sizes": ["S", "M", "L", "XL"]
      },
      {
        "id": 2,
        "name": "Classic White T-Shirt",
        "slug": "classic-white-t-shirt",
        "category": "T-Shirt",
        "price": 19.99,
        "originalPrice": 29.99,
        "discount": 33,
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
        "description": "Essential cotton white tee for everyday wear",
        "rating": 4.8,
        "inStock": true,
        "colors": ["White", "Black", "Gray"],
        "sizes": ["XS", "S", "M", "L", "XL", "XXL"]
      },
      {
        "id": 3,
        "name": "High-Waisted Blue Jeans",
        "slug": "high-waisted-blue-jeans",
        "category": "Jeans",
        "price": 79.99,
        "originalPrice": 120.00,
        "discount": 33,
        "image": "https://moioutfit.com/cdn/shop/files/93975-23123198.jpg?v=1702694584&width=1100",
        "additionalPhotos": [
          "https://moioutfit.com/cdn/shop/files/93978-23123201.jpg?v=1702694584&width=1100",
          "https://moioutfit.com/cdn/shop/files/93976-23123199.jpg?v=1702694584&width=535",
          "https://moioutfit.com/cdn/shop/files/93979-23123202.jpg?v=1702694583&width=535",
        ],
        "description": "Comfortable stretch denim with a flattering fit",
        "rating": 4.6,
        "inStock": true,
        "colors": ["Blue", "Black", "Light Blue"],
        "sizes": ["26", "28", "30", "32", "34"]
      },
      {
        "id": 4,
        "name": "Elegant Evening Dress",
        "slug": "elegant-evening-dress",
        "category": "Dress",
        "price": 89.00,
        "originalPrice": 150.00,
        "discount": 40,
        "image": "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500",
        "description": "Sophisticated dress for special occasions",
        "rating": 4.9,
        "inStock": true,
        "colors": ["Black", "Navy", "Burgundy"],
        "sizes": ["S", "M", "L"]
      },
      {
        "id": 5,
        "name": "Pleated Midi Skirt",
        "slug": "pleated-midi-skirt",
        "category": "Skirt",
        "price": 52.00,
        "originalPrice": 75.00,
        "discount": 30,
        "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500",
        "description": "Elegant pleated skirt with a flowing silhouette",
        "rating": 4.4,
        "inStock": true,
        "colors": ["Beige", "Black", "Green"],
        "sizes": ["S", "M", "L", "XL"]
      },
      {
        "id": 6,
        "name": "Graphic Print T-Shirt",
        "slug": "graphic-print-t-shirt",
        "category": "T-Shirt",
        "price": 24.99,
        "originalPrice": 35.00,
        "discount": 28,
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500",
        "description": "Trendy graphic tee with modern design",
        "rating": 4.3,
        "inStock": true,
        "colors": ["White", "Black", "Navy"],
        "sizes": ["S", "M", "L", "XL"]
      },
      {
        "id": 7,
        "name": "Slim Fit Black Jeans",
        "slug": "slim-fit-black-jeans",
        "category": "Jeans",
        "price": 69.99,
        "originalPrice": 95.00,
        "discount": 26,
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500",
        "description": "Sleek black jeans with a modern slim fit",
        "rating": 4.7,
        "inStock": true,
        "colors": ["Black"],
        "sizes": ["28", "30", "32", "34", "36"]
      },
      {
        "id": 8,
        "name": "Floral Maxi Dress",
        "slug": "floral-maxi-dress",
        "category": "Dress",
        "price": 75.00,
        "originalPrice": 110.00,
        "discount": 31,
        "image": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500",
        "description": "Beautiful floral print maxi dress for summer",
        "rating": 4.8,
        "inStock": true,
        "colors": ["Floral Blue", "Floral Pink", "Floral Green"],
        "sizes": ["XS", "S", "M", "L"]
      },
      {
        "id": 9,
        "name": "Denim Mini Skirt",
        "slug": "denim-mini-skirt",
        "category": "Skirt",
        "price": 38.00,
        "originalPrice": 55.00,
        "discount": 30,
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500",
        "description": "Classic denim mini skirt with button detail",
        "rating": 4.2,
        "inStock": true,
        "colors": ["Light Blue", "Dark Blue"],
        "sizes": ["S", "M", "L"]
      },
      {
        "id": 10,
        "name": "Striped V-Neck T-Shirt",
        "slug": "striped-v-neck-t-shirt",
        "category": "T-Shirt",
        "price": 27.99,
        "originalPrice": 40.00,
        "discount": 30,
        "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500",
        "description": "Casual striped tee with flattering v-neck",
        "rating": 4.5,
        "inStock": true,
        "colors": ["Navy/White", "Black/White", "Red/White"],
        "sizes": ["XS", "S", "M", "L", "XL"]
      },
      {
        "id": 11,
        "name": "Distressed Boyfriend Jeans",
        "slug": "distressed-boyfriend-jeans",
        "category": "Jeans",
        "price": 85.00,
        "originalPrice": 125.00,
        "discount": 32,
        "image": "https://images.unsplash.com/photo-1475178626620-a4d074967452?w=500",
        "description": "Relaxed fit jeans with trendy distressed details",
        "rating": 4.4,
        "inStock": true,
        "colors": ["Light Blue", "Medium Blue"],
        "sizes": ["26", "28", "30", "32"]
      },
      {
        "id": 12,
        "name": "Cocktail Party Dress",
        "slug": "cocktail-party-dress",
        "category": "Dress",
        "price": 95.00,
        "originalPrice": 140.00,
        "discount": 32,
        "image": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500",
        "description": "Chic cocktail dress perfect for evening events",
        "rating": 4.7,
        "inStock": true,
        "colors": ["Red", "Black", "Emerald"],
        "sizes": ["S", "M", "L"]
      },
      {
        "id": 13,
        "name": "A-Line Skirt",
        "slug": "a-line-skirt",
        "category": "Skirt",
        "price": 42.00,
        "originalPrice": 60.00,
        "discount": 30,
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500",
        "description": "Versatile A-line skirt for office or casual wear",
        "rating": 4.6,
        "inStock": false,
        "colors": ["Black", "Navy", "Camel"],
        "sizes": ["S", "M", "L", "XL"]
      },
      {
        "id": 14,
        "name": "Oversized Cotton T-Shirt",
        "slug": "oversized-cotton-t-shirt",
        "category": "T-Shirt",
        "price": 22.99,
        "originalPrice": 32.00,
        "discount": 28,
        "image": "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500",
        "description": "Comfortable oversized tee with relaxed fit",
        "rating": 4.6,
        "inStock": true,
        "colors": ["White", "Gray", "Pink", "Mint"],
        "sizes": ["S", "M", "L", "XL"]
      },
      {
        "id": 15,
        "name": "Skinny Ankle Jeans",
        "slug": "skinny-ankle-jeans",
        "category": "Jeans",
        "price": 72.00,
        "originalPrice": 100.00,
        "discount": 28,
        "image": "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=500",
        "description": "Flattering skinny jeans with ankle length",
        "rating": 4.5,
        "inStock": true,
        "colors": ["Dark Blue", "Black", "Gray"],
        "sizes": ["26", "28", "30", "32", "34"]
      },
      {
        "id": 16,
        "name": "Wrap Summer Dress",
        "slug": "wrap-summer-dress",
        "category": "Dress",
        "price": 68.00,
        "originalPrice": 95.00,
        "discount": 28,
        "image": "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=500",
        "description": "Flattering wrap dress with adjustable tie",
        "rating": 4.9,
        "inStock": true,
        "colors": ["Red Floral", "Blue Floral", "Green"],
        "sizes": ["XS", "S", "M", "L", "XL"]
      },
      {
        "id": 17,
        "name": "Leather Look Skirt",
        "slug": "leather-look-skirt",
        "category": "Skirt",
        "price": 55.00,
        "originalPrice": 80.00,
        "discount": 31,
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500",
        "description": "Edgy leather-look skirt with zipper detail",
        "rating": 4.3,
        "inStock": true,
        "colors": ["Black", "Brown"],
        "sizes": ["S", "M", "L"]
      },
      {
        "id": 18,
        "name": "Crop Fitted T-Shirt",
        "slug": "crop-fitted-t-shirt",
        "category": "T-Shirt",
        "price": 18.99,
        "originalPrice": 28.00,
        "discount": 32,
        "image": "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500",
        "description": "Trendy crop top with fitted silhouette",
        "rating": 4.4,
        "inStock": true,
        "colors": ["White", "Black", "Pink", "Lime"],
        "sizes": ["XS", "S", "M", "L"]
      },
      {
        "id": 19,
        "name": "Wide Leg Jeans",
        "slug": "wide-leg-jeans",
        "category": "Jeans",
        "price": 88.00,
        "originalPrice": 130.00,
        "discount": 32,
        "image": "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=500",
        "description": "Trendy wide leg jeans with vintage vibe",
        "rating": 4.6,
        "inStock": true,
        "colors": ["Light Blue", "Medium Blue"],
        "sizes": ["26", "28", "30", "32", "34"]
      },
      {
        "id": 20,
        "name": "Little Black Dress",
        "slug": "little-black-dress",
        "category": "Dress",
        "price": 79.00,
        "originalPrice": 115.00,
        "discount": 31,
        "image": "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=500",
        "description": "Timeless little black dress for any occasion",
        "rating": 5.0,
        "inStock": true,
        "colors": ["Black"],
        "sizes": ["XS", "S", "M", "L"]
      }
    ],
    "categories": [
      {
        "id": "all",
        "name": "All",
        "slug": "all"
      },
      {
        "id": "skirt",
        "name": "Skirt",
        "slug": "skirt"
      },
      {
        "id": "t-shirt",
        "name": "T-Shirt",
        "slug": "t-shirt"
      },
      {
        "id": "jeans",
        "name": "Jeans",
        "slug": "jeans"
      },
      {
        "id": "dress",
        "name": "Dress",
        "slug": "dress"
      }
    ]
  };

  return NextResponse.json(data);
}